### ISSUE TITLE
php-gd isn't configured

### ISSUE THREAD

**Issue by AJenbo** [mkenney/docker-php-base#1]
GD needs to be configured before it is installed, also the libwebp-dev dependency is missing:

Somthing like this should fix it:

RUN apt-get update \
    && apt-get install -y libwebp-dev \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-webp-dir=/usr/include/
    && docker-php-ext-install -j$(nproc) gd

**Comment by mkenney** [comment]
Awesome, I'll take a look as soon as I can, I should be able to address it this week.

**Comment by mkenney** [comment]
Here's [the pr](https://github.com/mkenney/docker-php-base/pull/2). With that build full GD support should be available:
```
GD support enabled                      Yes
GD Version                              bundled (2.1.0 compatible)
FreeType Support                        Yes
FreeType Linkage                        Yes
GIF Read Support                        Yes
GIF Create Support                      Yes
JPEG Support                            Yes
PNG Support                             Yes
WBMP Support                            Yes
XPM Support                             Yes
XBM Support                             Yes
WebP Support                            Yes
JIS-mapped Japanese Font Support        Yes
```
I also had to add `xpm` support to get `webp` to work in the php5 image.

I added a [travis-ci build](https://travis-ci.org/mkenney/docker-php-base) to validate GD support. Let me know if you have any trouble, and thank you.
